import { Component, OnInit, EventEmitter, Output } from '@angular/core';

@Component({
  selector: 'app-input-button-unit',
  template: `
    <input #inputElementRef class = "todo-input"
           [value]  = ""
           (keyup.enter)="submitTitle($event.target.value)">
    <button (click)='submitTitle(inputElementRef.value)' class ="btn">Save</button>

    `,
  styleUrls: ['./input-button-unit.component.css']
})
export class InputButtonUnitComponent implements OnInit {

  title: string;

  @Output() submit: EventEmitter<string> = new EventEmitter();

  constructor() { }

  ngOnInit(){};

  submitTitle(title: string){
    this.submit.emit(title); //Wysyła info
  }

  generateTitle(): string {
    return 'This title was generated by a method.';
  }

}
